### ISSUE TITLE
テーブルのカラム、APIの型を一致させる

### ISSUE THREAD

**Issue by taira51** [YT-travelers/spot-share#31]
# table_definition.md
https://github.com/YT-travelers/spot-share/blob/master/docs/table_definition.md

- スネークケース　→　キャメルケース（カラム名とテーブル名）
- id → ○○Id
- スポットテーブル.memo　→　summary

**↑は大脇の方で対応済み** 

# PHP My Admin

- スネークケース　→　キャメルケース（カラム名とテーブル名）
- id → ○○Id
- スポットテーブル.memo　→　summary

# stoplight
https://nolit.stoplight.io/docs/spot-share/branches/staging/api_definition.yaml/components/schemas/SimpleRoute

- https://github.com/YT-travelers/spot-share/blob/master/docs/table_definition.md に合わせる

**Comment by Nolit** [comment]
Laravel・JPAではスネークケースがデフォルト
MySQLもスネークケースが多く使われているようなのでカラム名をスネークケースにすることで合意
既にスネークケースとなっているので終了とする
