### ISSUE TITLE
ルート詳細のPOSTとGETで型が違う

### ISSUE THREAD

**Issue by taira51** [YT-travelers/spot-share#33]
Post a route wtih routeDetails のリクエストボディの型と
Get a Route with routeDetails のレスポンスの型が

一致していない。

リクエスト時の型を、レスポンス時の型の方に統一する。

### 現在の型（修正前）
POST/PATCH（リクエスト）
`route.routeDetails[0].spotId`

GET（レスポンス）
`route.routeDetails[0].spot.spotId`

### 期待する型（修正後）
POST/PATCH（リクエスト）
`route.routeDetails[0].spot.spotId`

GET（レスポンス）
`route.routeDetails[0].spot.spotId`

**Comment by Nolit** [comment]
リクエストとレスポンスの型を同じにしてdevelopブランチにマージ済み  
終了とする
