### ISSUE TITLE
angular 実行用コマンドの共有

### ISSUE THREAD

**Issue by Nolit** [YT-travelers/spot-share#39]
このチケットの後で #37 の対応を行います
### たいらにしてほしいこと
CI/CDにangularの起動も入れたいので、Githubからcloseした後に必要なコマンド教えてください  

### たいらにできればしてほしいこと
たいらのローカル環境で、GithubからのCloneと前述のコマンド実行を行って動作確認してもらえると助かります(node_modulesの内容がpackage.jsonに反映されてなかったりする為)
面倒だったらこちらで動作確認しながらやるのでコマンドだけ教えてください

**Comment by taira51** [comment]
Wikiにフロントの環境構築手順を記載
https://github.com/YT-travelers/spot-share/wiki/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%EF%BC%88%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%EF%BC%89

1回だけでよいコマンドと毎回実行する必要があるコマンドを、確認しながら連携する。
