### ISSUE TITLE
コード管理テーブルのクラス生成ツール

### ISSUE THREAD

**Issue by taira51** [YT-travelers/spot-share#41]
TypeScriptとphp(?)用の2つを作成する必要がある。

Typescriptは下記のnamespaceを使用する方針。

> 名前空間で（namespaceでクラス拡張）
> https://qiita.com/ConquestArrow/items/5d885128f896844698dd
> Enumに関数を追加
> https://blog.mitsuruog.info/2018/01/typescript-emun-tips

php(?)は水薮に確認する。（クラスのサンプルを作ってもらう）

また、コード管理テーブルからの情報取得は以下２案（要検討）

・コード管理情報をHTTPでGETしてjsonからクラスに変換
・コード管理情報をCSVに落とし、クラスに変換

**Comment by Nolit** [comment]
こういうファイルが出来上がると助かる！

```php:CuisineGenre.php

<?php

namespace App\Value;

class CuisineGenre
{
    const Seafood = 0;
    const FishDishes = 1;
}

```

**Comment by taira51** [comment]
バックエンドの自動生成はVer2以降で行うため、Clsoe
https://github.com/YT-travelers/spot-share/issues/83
