### ISSUE TITLE
ルート詳細更新に関する変更(複合主キー・orderカラムの削除)

### ISSUE THREAD

**Issue by Nolit** [YT-travelers/spot-share#51]
### 概要
[このissue](https://github.com/YT-travelers/spot-share/issues/32)でroute_detailsテーブルに関して以下の方針が決まった

* route_idとroute_detail_idを複合主キーにする
* orderカラムを廃止し、route_detail_idで順番を表す

**Comment by taira51** [comment]
内容確認済み
対応お願いします。

**Comment by Nolit** [comment]
たいらに以下の内容をLineで連絡した

```
[題名]
RouteDetailsをrouteIdとrouteDetailIdで複合主キーにするのは止めたい

[なぜ止めたいか]
今開発しててんけど、思ったより面倒くさい上に今後もめんどくさそうやから他の方法にしたらあかん？
routeDetailTourismsテーブルの外部キーをrouteDetailId単体からrouteIdとrouteDetailIdの複合キーにしなあかんねん
LaravelでDBを操作するメソッドも主キーが一つであることを前提にしてるっぽい

[代わりの案]
routeDetailの主キーをrouteDetailIdだけにしておいても、routeDetailIdの並び順でソートできると思うねん
```

**Comment by Nolit** [comment]
### 話し合いの結果
実装方針は水薮に任せることとなった
問題が起こりそうなものの、今まで試したことが無かったので以下で実装する

* route_idとroute_detail_idとの複合主キーを作成
* orderカラムは削除
* route_detail_idはphp側でroute_idごとに一意に作成する

**Comment by Nolit** [comment]
実装して本番環境にデプロイした
クライアントの方で動作確認もできたのでCloseする
