### ISSUE TITLE
ルート詳細登録・更新時にマスタデータを作成する機能を削除する

### ISSUE THREAD

**Issue by Nolit** [YT-travelers/spot-share#52]
### 概要
ルート詳細を登録・更新するAPIでは以下の処理を行っている

1. リクエスト内のルート詳細に紐づくマスタIDを確認
    * 例)routeDetail.routeDetailTourism.tourismIdを確認
2. マスタIDがnullの場合、新しくマスタを作成しルート詳細に紐づける

しかし現状、ルート詳細を作成する時は必ず先にマスタデータを作成するとのこと(たいらより)
上記機能は不要なので削除する

**Comment by taira51** [comment]
確認しました。
対応お願いします。

**Comment by Nolit** [comment]
該当コードを削除してデプロイしたのでCloseする
