### ISSUE TITLE
時間に関するデータの変更

### ISSUE THREAD

**Issue by Nolit** [YT-travelers/spot-share#68]
### 概要
フロントが扱いやすいように時間に関する以下の変更を行う

* ホテル以外の3つのメインビーン(マスタ)の営業開始時間は時間と分で分ける
* レストラン・アクティビティの開始時間と終了時間は削除する

**Comment by taira51** [comment]
>ホテル以外の3つのメインビーン(マスタ)の営業開始時間は時間と分で分ける

追加で、マスタじゃないんやけどRouteDetailHotelの

hotelCheckInTime
hotelCheckOutTime

も

hotelCheckInTimeHour
hotelCheckOutTimeHour
hotelCheckInTimeMinutes
hotelCheckOutTimeMinutes

に分解したい

**Comment by Nolit** [comment]
### スキーマの変更点
以下の変更を行った
(`-`が削除された値、`+`が追加された値)

**Restaurantスキーマ**

```
- restaurantOpenTime
- restaurantCloseTime
+ restaurantOpenTimeHours
+ restaurantOpenTimeMinutes
+ restaurantCloseTimeHours
+ restaurantCloseTimeMinutes
```

**Tourismスキーマ**

```
- tourismOpenTime
- tourismCloseTime
+ tourismOpenTimeHours
+ tourismOpenTimeMinutes
+ tourismCloseTimeHours
+ tourismCloseTimeMinutes
```

**RouteDetailHotelスキーマ**

```
- hotelCheckInTime
- hotelCheckOutTime
+ hotelCheckInTimeHours
+ hotelCheckInTimeMinutes
+ hotelCheckOutTimeHours
+ hotelCheckOutTimeMinutes
```

**RouteDetailRestaurantスキーマ**

```
- restaurantStartTime
- restaurantEndTime
```

**Activityスキーマ**

```
- activityOpenTime
- activityCloseTime
+ activityOpenTimeHours
+ activityOpenTimeMinutes
+ activityCloseTimeHours
+ activityCloseTimeMinutes
```

**RouteDetailActivityスキーマ**

```
- activityStartTime
- activityEndTime
```
