### ISSUE TITLE
観光地マスタ　入力必須じゃない項目が未入力だとエラーが返却される

### ISSUE THREAD

**Issue by taira51** [YT-travelers/spot-share#71]
返却されるエラー内容
```
"message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tourism_summary' cannot be null (SQL: insert into `tourisms` (`tourism_name`, `tourism_open_time_hours`, `tourism_open_time_minutes`, `tourism_close_time_hours`, `tourism_close_time_minutes`, `tourism_summary`, `tourism_address`, `tourism_url`, `country_code`, `updated_at`, `created_at`) values (テスト, ?, ?, ?, ?, ?, ?, ?, ABW, 2021-05-03 06:09:57, 2021-05-03 06:09:57))",
```

・tourism_summary
・tourism_address
・tourism_url

の項目で同様の事象を確認。
該当項目は入力必須ではない認識。（修正自体は #65 と同じになるんかな）

現時点でtourismマスタのみ確認できてるけど、
出来れば横展開でほかのマスタも確認して、問題があれば修正しておいてほしい。

**Comment by Nolit** [comment]
### 原因
クライアントからのリクエストで該当項目がnullになっていた

### 対応
暫定対応としてデータベース上でNULLを認めるようにする

**Comment by Nolit** [comment]
### 変更点
それぞれのスキーマでnullが認められるように変更した

**Hotel**

* hotel_summary
* hotel_address
* hotel_url

**Restaurant**

* restaurant_summary
* restaurant_address
* restaurant_url

**Tourism**

* tourism_summary
* tourism_address
* tourism_url

**Comment by Nolit** [comment]
修正完了した
そちらのタイミングでCloseねがいます

**Comment by taira51** [comment]
障害解消確認済
