### ISSUE TITLE
スポットの画像に関するAPI作成

### ISSUE THREAD

**Issue by Nolit** [YT-travelers/spot-share#8]
スポット登録時の大まかなフローは以下の通り。

①（フロント）スポット登録画面で"保存"ボタン押下により、画像アップロードAPIを呼び出す
②（バック）画像アップロードAPIが画像をDBに格納し、パスを返却。
③（フロント）画像アップロードAPIから返却されたパスをスポットの情報に設定しスポットAPIをリクエスト。
④（バック）スポットAPIがスポットの情報をDBに格納。

観光地、飲食店、ホテル、アクティビティテーブルの定義を更新する必要あり。
スプレッドシートと併せて更新よろしく。
https://docs.google.com/spreadsheets/d/1FeesX4Z6D1y_zF_uoxda3v1YMngDjrbt10kEmUWpcLc/edit#gid=0

■関連Issue
https://github.com/YT-travelers/spot-share/issues/15

**Comment by Nolit** [comment]
### 構成
* ファイルはS3に保存する
* 実装時間を考慮して、ブラウザ->appサーバ->S3の流れでアップロードする
* セキュリティを考慮して、ダウンロード時に署名付きURLを使用する
* 料金を考慮して、特定の容量を超えるとアップロードできないようにする

### アップロードの流れ
* マスタデータと合わせてファイルをPOSTする
* サーバはファイルをS3へアップロード
* オブジェクトキーをDBに保存

### ダウンロードの流れ
* サーバからマスタデータと合わせて署名付きURLを取得
* 署名付きURLを使用してS3からダウンロード

### TODO
* バケット・S3用のIAMをCloudFormationで作成
* 署名付きURLを発行(ダウンロード用)
* URLを共有してダウンロードできるか確認してもらう
* テーブル構成の変更
* サーバーサイドの修正

**Comment by Nolit** [comment]
### スキーマの変更点
以下の変更を行った
(`-`が削除された値、`+`が追加された値)

**Activityスキーマ**

```
+ activityImages
+ uploadFiles
```

**ActivityImageスキーマ**

```
スキーマ自体を新規作成
```

**Tourismスキーマ**

```
+ tourismImages
+ uploadFiles
```

**TourismImageスキーマ**

```
スキーマ自体を新規作成
```

**Restaurantスキーマ**

```
+ restaurantImages
+ uploadFiles
```

**RestaurantImageスキーマ**

```
スキーマ自体を新規作成
```

**Hotelスキーマ**

```
+ hotelImages
+ uploadFiles
```

**HotelImageスキーマ**

```
スキーマ自体を新規作成
```

**Comment by Nolit** [comment]
残作業は以下で対応するからこのチケットはCloseで良いかと思う

* #77 
* #76 

一応当初と話がズレてないか確認してCloseお願い

**Comment by taira51** [comment]
確認できたのでClose

画像アップロードの仕様は下記参照。
[画像アップロード（削除）方式仕様](https://github.com/YT-travelers/spot-share/wiki/%E7%94%BB%E5%83%8F%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%EF%BC%88%E5%89%8A%E9%99%A4%EF%BC%89%E6%96%B9%E5%BC%8F%E4%BB%95%E6%A7%98)
